// BUG in 0,29 ->  "[Script] Error: An element with the same key already exists in the dictionary.",

const config = {
  MAX_PODS: 90,
  ELEMENTS_TO_GATHER: [ 71, 74, 75, 76, 77, 78, 80, 79, 81, 100, 136, 132 ],
  OPEN_BAGS: true
}

const move= [
	{ map : "1,-21", path : "bottom" },
	{ map : "1,-20", path : "bottom" },
	{ map : "2,-22", path : "bottom" },
	{ map : "2,-21", path : "bottom" },
	{ map : "3,-22", path : "bottom" },
	{ map : "3,-21", path : "bottom" },
	{ map : "3,-20", path : "bottom" },
	{ map : "2,-20", path : "bottom" },
	{ map : "3,-16", path : "right" },
	{ map : "4,-16", path : "top" },
	{ map : "4,-17", path : "top" },
	{ map : "4,-18", path : "top" },
	{ map : "6,-20", path : "bottom" },
	{ map : "6,-16", path : "top" },
	{ map : "6,-17", path : "top" },
	{ map : "6,-18", path : "top" },
	{ map : "7,-15", path : "top" },
	{ map : "7,-16", path : "top" },
	{ map : "7,-17", path : "top" },
	{ map : "7,-18", path : "top" },
	{ map : "7,-21", path : "bottom" },
	{ map : "7,-20", path : "bottom" },
  { map : "-1,-14", path : "top" },
	{ map : "-1,-15", path : "top" },
	{ map : "-1,-16", path : "top" },
	{ map : "-1,-17", path : "right" },
	{ map : "0,-17", path : "top" },
	{ map : "0,-18", path : "top" },
	{ map : "0,-19", path : "right" },
	{ map : "1,-19", path : "right" },
	{ map : "2,-19", path : "right" },
	{ map : "3,-19", path : "right" },
	{ map : "4,-19", path : "right" },
	{ map : "5,-19", path : "right" },
	{ map : "6,-19", path : "right" },
	{ map : "7,-19", path : "right" },
	{ map : "8,-19", path : "bottom" },
	{ map : "8,-18", path : "bottom" },
	{ map : "8,-17", path : "bottom" },
	{ map : "8,-16", path : "bottom" },
	{ map : "8,-15", path : "bottom" },
	{ map : "8,-14", path : "bottom" },
	{ map : "8,-13", path : "left" },
	{ map : "7,-13", path : "left" },
	{ map : "6,-13", path : "left" },
	{ map : "5,-13", path : "left" },
	{ map : "4,-13", path : "bottom" },
	{ map : "4,-12", path : "bottom" },
	{ map : "4,-11", path : "bottom" },
	{ map : "4,-10", path : "bottom" },
	{ map : "4,-9", path : "bottom" },
	{ map : "4,-8", path : "bottom" },
	{ map : "4,-7", path : "bottom" },
	{ map : "4,-6", path : "left" },
	{ map : "3,-6", path : "bottom" },
	{ map : "3,-5", path : "right" },

	{ map : "4,-5", path : "bottom" },
	{ map : "4,-4", path : "bottom" },
	{ map : "4,-3", path : "bottom" },
	{ map : "4,-2", path : "right" },
	{ map : "5,-2", path : "right" },
	{ map : "6,-2", path : "right" },
	{ map : "7,-2", path : "bottom" },
	{ map : "7,-1", path : "bottom" },
	{ map : "7,0", path : "bottom" },
	{ map : "7,1", path : "bottom" },
	{ map : "7,2", path : "bottom" },
	{ map : "7,3", path : "bottom" },
	{ map : "7,4", path : "bottom" },
	{ map : "7,5", path : "bottom" },
	{ map : "7,6", path : "bottom" },
	{ map : "7,7", path : "bottom" },
	{ map : "7,8", path : "bottom" },
	{ map : "7,9", path : "bottom" },
	{ map : "7,10", path : "right" },
	{ map : "8,10", path : "right" },
	{ map : "9,10", path : "right" },
	{ map : "10,10", path : "right" },
	{ map : "11,10", path : "right" },

	{ map : "12,10", gather : true, path : "bottom" },
	{ map : "12,11", gather : true, path : "bottom" },
	{ map : "12,12", gather : true, path : "left" },
	{ map : "11,12", gather : true, path : "bottom|left|left" },
	{ map : "11,13", gather : true, path : "top" },
	{ map : "10,12", gather : true, path : "left" },
	{ map : "9,12", gather : true, path : "bottom" },
	{ map : "9,13", gather : true, path : "left" },
	{ map : "8,13", gather : true, path : "bottom" },
	{ map : "8,14", gather : true, path : "left" },
	{ map : "7,14", gather : true, path : "bottom" },
	{ map : "7,15", gather : true, path : "bottom" },
	{ map : "7,16", gather : true, path : "bottom" },
	{ map : "7,17", gather : true, path : "bottom" },
	{ map : "7,18", gather : true, path : "right" },
	{ map : "8,18", gather : true, path : "bottom" },

	{ map : "8,19", gather : true, path : "right" },
	{ map : "9,19", gather : true, path : "top|right|right" },
	{ map : "9,18", gather : true, path : "bottom" },
	{ map : "10,19", gather : true, path : "bottom" },
	{ map : "10,20", path : "bottom" },
	{ map : "10,21", path : "bottom" },
	{ map : "10,22", path : "left" },
	{ map : "9,22", gather : true, path : "left" },
	{ map : "8,22", gather : true, path : "left" },
	{ map : "7,22", path : "bottom" },
	{ map : "7,23", gather : true, path : "left" },
	{ map : "6,23", gather : true, path : "left" },
	{ map : "5,23", gather : true, path : "left" },
	{ map : "4,23", path : "bottom" },

	{ map : "4,24", gather : true, path : "bottom" },
	{ map : "4,25", gather : true, path : "bottom" },
	{ map : "4,26", path : "right" },
	{ map : "5,26", gather : true, path : "bottom" },
	{ map : "5,27", gather : true, path : "bottom" },
	{ map : "5,28", path : "right" },
	{ map : "6,28", gather : true, path : "right" },
	{ map : "7,28", gather : true, path : "bottom" },
	{ map : "7,29", gather : true, path : "right" },
	{ map : "8,29", gather : true, path : "right" },
	{ map : "9,29", gather : true, path : "top" },
	{ map : "9,28", gather : true, path : "right" },
	{ map : "10,28", gather : true, path : "right" },
	{ map : "11,28", gather : true, path : "bottom" },
	{ map : "11,29", gather : true, path : "bottom|left|left" },
	{ map : "11,30", gather : true, path : "top" },
	{ map : "10,29", path : "bottom" },
	{ map : "10,30", gather : true, path : "left" },
	{ map : "9,30", gather : true, path : "left" },
	{ map : "8,30", path : "bottom" },
	{ map : "8,31", gather : true, path : "left" },
	{ map : "7,31", gather : true, path : "left" },
	{ map : "6,31", gather : true, path : "left" },
	{ map : "5,31", gather : true, path : "bottom" },
	{ map : "5,32", gather : true, path : "left" },
	{ map : "4,32", gather : true, path : "left" },
	{ map : "3,32", gather : true, path : "left" },
	{ map : "2,32", gather : true, path : "top" },
	{ map : "2,31", path : "left" },
	{ map : "1,31", gather : true, path : "bottom|top|top" },
	{ map : "1,30", path : "left" },
	{ map : "0,30", gather : true, path : "top" },
	{ map : "0,29", gather : true, path : "top" },
	{ map : "0,28", gather : true, path : "top" },
	{ map : "0,27", gather : true, path : "top" },
	{ map : "0,26", gather : true, path : "top" },
	{ map : "0,25", gather : true, path : "top" },
	{ map : "0,24", gather : true, path : "left|right" },
	{ map : "-1,24", gather : true, path : "top" },
	{ map : "-1,23", path : "right" },
	{ map : "0,23", path : "right" },
	{ map : "1,23", path : "top" },
	{ map : "1,22", path : "top" },
	{ map : "1,21", path : "top" },
	{ map : "1,20", path : "top" },
	{ map : "1,19", path : "top|right" },
	{ map : "1,18", path : "top" },
	{ map : "1,17", path : "top" },
	{ map : "1,16", path : "top" },
	{ map : "1,15", path : "top" },
	{ map : "1,14", path : "top" },
	{ map : "1,13", path : "top" },
	{ map : "-1,13", path : "right" },
	{ map : "0,13", path : "right" },
	{ map : "1,12", path : "top" },
	{ map : "1,11", path : "top" },
	{ map : "1,10", path : "right" },
	{ map : "2,10", path : "right" },
	{ map : "3,10", path : "right" },
	{ map : "4,10", path : "right" },
	{ map : "5,10", path : "right" },
	{ map : "6,10", path : "right" },

	{ map : "1,32", gather : true, path : "bottom" },
	{ map : "1,33", gather : true, path : "left" },
	{ map : "0,33", path : "bottom" },
	{ map : "0,34", gather : true, path : "left" },
	{ map : "-1,34", gather : true, path : "left" },
	{ map : "-2,34", gather : true, path : "top" },
	{ map : "-2,33", gather : true, path : "top" },
	{ map : "-2,32", gather : true, path : "top" },
	{ map : "-2,31", gather : true, path : "right" },
	{ map : "-1,31", gather : true, path : "right" },
	{ map : "0,31", gather : true, path : "right" },

	{ map : "7,-4", path : "bottom" },
	{ map : "7,-3", path : "bottom" },
	{ map : "5,7", path : "right" },
	{ map : "6,7", path : "right" },
	{ map : "7,13", path : "top" },
	{ map : "7,12", path : "top" },
	{ map : "7,11", path : "top" },
	{ map : "2,19", path : "right" },
	{ map : "3,19", path : "right" },
	{ map : "4,19", path : "right" },
	{ map : "5,19", path : "right" },
	{ map : "6,19", path : "right" },
	{ map : "7,19", path : "right" },
	{ map : "-2,0", path : "bottom" },
	{ map : "-2,1", path : "right" },
	{ map : "-1,1", path : "right" },
	{ map : "0,1", path : "bottom" },
	{ map : "0,2", path : "bottom" },
	{ map : "0,3", path : "right" },
	{ map : "1,3", path : "right" },
	{ map : "2,3", path : "right" },
	{ map : "3,3", path : "right" },
	{ map : "4,3", path : "right" },
	{ map : "5,3", path : "right" },
	{ map : "6,3", path : "right" },
	{ map : "-1,0", path : "bottom" },
	{ map : "-1,-1", path : "bottom" },
	{ map : "0,-1", path : "right" },
	{ map : "1,-1", path : "bottom" },
	{ map : "1,0", path : "bottom" },
	{ map : "1,1", path : "bottom" },
	{ map : "1,2", path : "bottom" },
	{ map : "3,-2", path : "left" },
	{ map : "2,-1", path : "bottom" },
	{ map : "2,0", path : "bottom" },
	{ map : "2,1", path : "bottom" },
	{ map : "2,2", path : "bottom" },
	{ map : "1,24", path : "right" },
	{ map : "2,24", path : "right" },
	{ map : "3,24", path : "right" },
	{ map : "5,7", path : "bottom" },
	{ map : "5,8", path : "bottom" },
	{ map : "5,9", path : "bottom" },
	{ map : "4,27", path : "right" },
	{ map : "88081177", path : "bottom" },
	{ map : "99095051", path : "410" }
];

const bank = [
	{ map : "1,-21", path : "bottom" },
	{ map : "1,-20", path : "bottom" },
	{ map : "2,-22", path : "bottom" },
	{ map : "2,-21", path : "bottom" },
	{ map : "3,-22", path : "bottom" },
	{ map : "3,-21", path : "bottom" },
	{ map : "3,-20", path : "bottom" },
	{ map : "2,-20", path : "bottom" },
	{ map : "3,-16", path : "right" },
	{ map : "4,-16", path : "top" },
	{ map : "4,-17", path : "top" },
	{ map : "4,-18", path : "top" },
	{ map : "6,-20", path : "bottom" },
	{ map : "6,-16", path : "top" },
	{ map : "6,-17", path : "top" },
	{ map : "6,-18", path : "top" },
	{ map : "7,-15", path : "top" },
	{ map : "7,-16", path : "top" },
	{ map : "7,-17", path : "top" },
	{ map : "7,-18", path : "top" },
	{ map : "7,-21", path : "bottom" },
	{ map : "7,-20", path : "bottom" },
  { map : "-1,-14", path : "top" },
	{ map : "-1,-15", path : "top" },
	{ map : "-1,-16", path : "top" },
	{ map : "-1,-17", path : "right" },
	{ map : "0,-17", path : "top" },
	{ map : "0,-18", path : "top" },
	{ map : "0,-19", path : "right" },
	{ map : "1,-19", path : "right" },
	{ map : "2,-19", path : "right" },
	{ map : "3,-19", path : "right" },
	{ map : "4,-19", path : "right" },
	{ map : "5,-19", path : "right" },
	{ map : "6,-19", path : "right" },
	{ map : "7,-19", path : "right" },
	{ map : "8,-19", path : "bottom" },
	{ map : "8,-18", path : "bottom" },
	{ map : "8,-17", path : "bottom" },
	{ map : "8,-16", path : "bottom" },
	{ map : "8,-15", path : "bottom" },
	{ map : "8,-14", path : "bottom" },
	{ map : "8,-13", path : "left" },
	{ map : "7,-13", path : "left" },
	{ map : "6,-13", path : "left" },
	{ map : "5,-13", path : "left" },
	{ map : "4,-13", path : "bottom" },
	{ map : "4,-12", path : "bottom" },
	{ map : "4,-11", path : "bottom" },
	{ map : "4,-10", path : "bottom" },
	{ map : "4,-9", path : "bottom" },
	{ map : "4,-8", path : "bottom" },
	{ map : "4,-7", path : "bottom" },
	{ map : "4,-6", path : "left" },
	{ map : "3,-6", path : "bottom" },
	{ map : "3,-5", path : "right" },


	{ map : "4,-5", path : "bottom" },
	{ map : "4,-4", path : "bottom" },
	{ map : "4,-3", path : "bottom" },
	{ map : "4,-2", path : "left" },
	{ map : "5,-2", path : "left" },
	{ map : "6,-2", path : "left" },
	{ map : "7,-2", path : "left" },
	{ map : "7,-1", path : "top" },
	{ map : "7,0", path : "top" },
	{ map : "7,1", path : "top" },
	{ map : "7,2", path : "top" },
	{ map : "7,3", path : "left" },
	{ map : "7,4", path : "top" },
	{ map : "7,5", path : "top" },
	{ map : "7,6", path : "top" },
	{ map : "7,7", path : "top" },
	{ map : "7,8", path : "top" },
	{ map : "7,9", path : "top" },
	{ map : "7,10", path : "top" },
	{ map : "8,10", path : "left" },
	{ map : "9,10", path : "left" },
	{ map : "10,10", path : "left" },
	{ map : "11,10", path : "left" },

	{ map : "12,10", path : "left" },
	{ map : "12,11", path : "top" },
	{ map : "12,12", path : "top" },
	{ map : "11,12", path : "right|left" },
	{ map : "11,13", path : "top" },
	{ map : "10,12", path : "left" },
	{ map : "9,12", path : "bottom" },
	{ map : "9,13", path : "left" },
	{ map : "8,13", path : "bottom" },
	{ map : "8,14", path : "left" },
	{ map : "7,14", path : "top" },
	{ map : "7,15", path : "top" },
	{ map : "7,16", path : "top" },
	{ map : "7,17", path : "top" },
	{ map : "7,18", path : "top" },
	{ map : "8,18", path : "left" },

	{ map : "8,19", path : "top" },
	{ map : "9,19", path : "left" },
	{ map : "9,18", path : "bottom" },
	{ map : "10,19", path : "left" },
	{ map : "10,20", path : "top" },
	{ map : "10,21", path : "top" },
	{ map : "10,22", path : "top" },
	{ map : "9,22", path : "right" },
	{ map : "8,22", path : "right" },
	{ map : "7,22", path : "right" },
	{ map : "7,23", path : "top" },
	{ map : "6,23", path : "right" },
	{ map : "5,23", path : "right" },
	{ map : "4,23", path : "right" },

	{ map : "4,24", path : "left" },
	{ map : "4,25", path : "top" },
	{ map : "4,26", path : "top" },
	{ map : "5,26", path : "left" },
	{ map : "5,27", path : "top" },
	{ map : "5,28", path : "top" },
	{ map : "6,28", path : "left" },
	{ map : "7,28", path : "left" },
	{ map : "7,29", path : "top" },
	{ map : "8,29", path : "left" },
	{ map : "9,29", path : "left" },
	{ map : "9,28", path : "bottom" },
	{ map : "10,28", path : "left" },
	{ map : "11,28", path : "left" },
	{ map : "11,29", path : "top" },
	{ map : "11,30", path : "top" },
	{ map : "10,29", path : "right" },
	{ map : "10,30", path : "top" },
	{ map : "9,30", path : "right" },
	{ map : "8,30", path : "right" },
	{ map : "8,31", path : "top" },
	{ map : "7,31", path : "left" },
	{ map : "6,31", path : "left" },
	{ map : "5,31", path : "bottom" },
	{ map : "5,32", path : "left" },
	{ map : "4,32", path : "left" },
	{ map : "3,32", path : "left" },
	{ map : "2,32", path : "top" },
	{ map : "2,31", path : "left" },
	{ map : "1,31", path : "top" },
	{ map : "1,30", path : "left" },
	{ map : "0,30", path : "top" },
	{ map : "0,29", path : "top" },
	{ map : "0,28", path : "top" },
	{ map : "0,27", path : "top" },
	{ map : "0,26", path : "top" },
	{ map : "0,25", path : "top" },
	{ map : "0,24", path : "top" },
	{ map : "-1,24", path : "top" },
	{ map : "-1,23", path : "right" },
	{ map : "0,23", path : "right" },
	{ map : "1,23", path : "top" },
	{ map : "1,22", path : "top" },
	{ map : "1,21", path : "top" },
	{ map : "1,20", path : "top" },
	{ map : "1,19", path : "right" },
	{ map : "1,18", path : "top" },
	{ map : "1,17", path : "top" },
	{ map : "1,16", path : "top" },
	{ map : "1,15", path : "top" },
	{ map : "1,14", path : "top" },
	{ map : "1,13", path : "top" },
	{ map : "-1,13", path : "right" },
	{ map : "0,13", path : "right" },
	{ map : "1,12", path : "top" },
	{ map : "1,11", path : "top" },
	{ map : "1,10", path : "right" },
	{ map : "2,10", path : "right" },
	{ map : "3,10", path : "right" },
	{ map : "4,10", path : "right" },
	{ map : "5,10", path : "right" },
	{ map : "6,10", path : "right" },

	{ map : "1,32", path : "top" },
	{ map : "1,33", path : "top" },
	{ map : "0,33", path : "right" },
	{ map : "0,34", path : "top" },
	{ map : "-1,34", path : "right" },
	{ map : "-2,34", path : "right" },
	{ map : "-2,33", path : "top" },
	{ map : "-2,32", path : "top" },
	{ map : "-2,31", path : "right" },
	{ map : "-1,31", path : "right" },
	{ map : "0,31", path : "right" },

	{ map : "7,-4", path : "bottom" },
	{ map : "7,-3", path : "bottom" },
	{ map : "5,7", path : "right" },
	{ map : "6,7", path : "right" },
	{ map : "7,13", path : "top" },
	{ map : "7,12", path : "top" },
	{ map : "7,11", path : "top" },
	{ map : "2,19", path : "right" },
	{ map : "3,19", path : "right" },
	{ map : "4,19", path : "right" },
	{ map : "5,19", path : "right" },
	{ map : "6,19", path : "right" },
	{ map : "7,19", path : "top" },
	{ map : "-2,0", path : "right" },
	{ map : "-2,1", path : "top" },
	{ map : "-1,1", path : "top" },
	{ map : "0,1", path : "right" },
	{ map : "0,2", path : "top" },
	{ map : "0,3", path : "top" },
	{ map : "1,3", path : "top" },
	{ map : "2,3", path : "top" },
	{ map : "3,3", path : "left" },
	{ map : "4,3", path : "left" },
	{ map : "5,3", path : "left" },
	{ map : "6,3", path : "left" },
	{ map : "-1,0", path : "top" },
	{ map : "-1,-1", path : "right" },
	{ map : "0,-1", path : "right" },
	{ map : "1,-1", path : "right" },
	{ map : "1,0", path : "top" },
	{ map : "1,1", path : "top" },
	{ map : "1,2", path : "top" },
	{ map : "3,-2", path : "left" },
	{ map : "2,-1", path : "top" },
	{ map : "2,0", path : "top" },
	{ map : "2,1", path : "top" },
	{ map : "2,2", path : "top" },
	{ map : "1,24", path : "top" },
	{ map : "2,24", path : "left" },
	{ map : "3,24", path : "left" },
	{ map : "5,7", path : "bottom" },
	{ map : "5,8", path : "bottom" },
	{ map : "5,9", path : "bottom" },
	{ map : "4,27", path : "right" },
	{ map : 88081177, door : 216 },
	{ map : 99095051, npcBank : true }
];
