const config = {
  MAX_PODS: 90,
  ELEMENTS_TO_GATHER: [ 75, 71, 74, 77, 76, 78, 79, 81, 264, 263 ],
  OPEN_BAGS: true
}

const move = [
  { map: "7,22", path: "right" },
  { map: "6,22", path: "right" },
  { map: "5,21", path: "bottom" },
  { map: "5,22", path: "right" },
  { map: "5,20", path: "bottom" },
  { map: "5,19", path: "bottom" },
  { map: "5,18", path: "bottom" },
  { map: "5,17", path: "bottom" },
  { map: "5,16", path: "bottom" },
  { map: "5,15", path: "bottom" },
  { map: "5,14", path: "bottom" },
  { map: "5,13", path: "bottom" },
  { map: "5,12", path: "bottom" },
  { map: "5,11", path: "bottom" },
  { map: "6,11", path: "left" },
  { map: "7,11", path: "left" },
  { map: "8,11", path: "left" },
  { map: "9,11", path: "left" },
  { map: "9,10", path: "bottom" },
  { map: "9,9", path: "bottom" },
  { map: "9,8", path: "bottom" },
  { map: "9,7", path: "bottom" },
  { map: "9,6", path: "bottom" },
  { map: "9,5", path: "bottom" },
  { map: "9,4", path: "bottom" },
  { map: "7,14", path: "right" },
  { map: "8,13", path: "right" },
  { map: "10,20", path: "left" },
  { map: "7,19", path: "top" },
  { map: "9,20", path: "top" },
  { map: "10,21", path: "top" },
  { map: "10,22", path: "top" },
  { map: "9,2", path: "bottom" },
  { map: "9,3", path: "bottom" },
  { map: "2,-1", path: "bottom" },
  { map: "2,0", path: "bottom" },
  { map: "2,1", path: "bottom" },
  { map: "2,2", path: "bottom" },
  { map: "2,3", path: "right" },
  { map: "3,3", path: "right" },
  { map: "4,3", path: "right" },
  { map: "5,3", path: "right" },
  { map: "6,3", path: "right" },
  { map: "7,3", path: "right" },
  { map: "8,3", path: "right" },
  { map: "9,22", path: "right", gather: true },
  { map: "8,22", path: "right", gather: true },
  { map: "11,12", path: "right", gather: true },
  { map: "10,12", path: "right", gather: true },
  { map: "9,12", path: "right", gather: true },
  { map: "9,13", path: "top", gather: true },
  { map: "8,14", path: "top", gather: true },
  { map: "7,15", path: "top", gather: true },
  { map: "7,16", path: "top", gather: true },
  { map: "7,17", path: "top", gather: true },
  { map: "7,18", path: "top", gather: true },
  { map: "8,19", path: "left", gather: true },
  { map: "9,19", path: "left", gather: true },
  { map: "12,12", path: "top", gather: true },
  { map: "12,11", path: "top", gather: true },
  { map: "12,10", path: "left", gather: true },
  { map: "11,10", path: "top" },
  { map: "11,9", path: "right" },
  { map: "12,9", path: "top", gather: true },
  { map: "12,8", path: "right", gather: true },
  { map: "13,8", path: "top", gather: true },
  { map: "13,7", path: "top", gather: true },
  { map: "13,6", path: "top", gather: true },
  { map: "13,5", path: "top", gather: true },
  { map: "13,4", path: "left", gather: true },
  { map: "12,3", path: "left", gather: true },
  { map: "12,4", path: "left", gather: true },
  { map: "11,4", path: "top" },
  { map: "11,3", path: "left", gather: true },
  { map: "10,1", path: "left", gather: true },
  { map: "9,1", path: "bottom", gather: true },
  { map: "10,3", path: "top", gather: true },
  { map: "10,2", path: "left", gather: true },
  { map: "88081177", path: "bottom" },
  { map: "99095051", path: "410" },
]

const bank = [
  { map: "5,12", path: "top" },
  { map: "5,13", path: "top" },
  { map: "5,14", path: "top" },
  { map: "5,15", path: "top" },
  { map: "5,16", path: "top" },
  { map: "5,17", path: "top" },
  { map: "5,18", path: "top" },
  { map: "5,19", path: "top" },
  { map: "5,20", path: "top" },
  { map: "5,21", path: "top" },
  { map: "5,22", path: "top" },
  { map: "10,21", path: "top" },
  { map: "7,15", path: "top" },
  { map: "7,16", path: "top" },
  { map: "7,17", path: "top" },
  { map: "7,18", path: "top" },
  { map: "7,19", path: "top" },
  { map: "8,14", path: "top" },
  { map: "8,13", path: "right" },
  { map: "7,14", path: "right" },
  { map: "8,19", path: "left" },
  { map: "9,19", path: "left" },
  { map: "10,20", path: "left" },
  { map: "6,22", path: "left" },
  { map: "7,22", path: "left" },
  { map: "8,22", path: "left" },
  { map: "9,22", path: "left" },
  { map: "10,22", path: "left" },
  { map: "8,11", path: "right" },
  { map: "7,11", path: "right" },
  { map: "6,11", path: "right" },
  { map: "5,11", path: "right" },
  { map: "10,12", path: "left" },
  { map: "11,12", path: "left" },
  { map: "9,13", path: "top" },
  { map: "9,12", path: "top" },
  { map: "9,4", path: "top" },
  { map: "9,5", path: "top" },
  { map: "9,6", path: "top" },
  { map: "9,7", path: "top" },
  { map: "9,8", path: "top" },
  { map: "9,9", path: "top" },
  { map: "9,10", path: "top" },
  { map: "9,11", path: "top" },
  { map: "12,3", path: "left" },
  { map: "11,3", path: "left" },
  { map: "10,3", path: "left" },
  { map: "10,2", path: "left" },
  { map: "10,1", path: "left" },
  { map: "13,4", path: "left" },
  { map: "12,4", path: "left" },
  { map: "11,4", path: "top" },
  { map: "9,1", path: "bottom" },
  { map: "9,2", path: "bottom" },
  { map: "9,3", path: "left" },
  { map: "8,3", path: "left" },
  { map: "7,3", path: "left" },
  { map: "6,3", path: "left" },
  { map: "5,3", path: "left" },
  { map: "4,3", path: "left" },
  { map: "3,3", path: "left" },
  { map: "2,3", path: "top" },
  { map: "2,2", path: "top" },
  { map: "2,1", path: "top" },
  { map: "2,0", path: "top" },
  { map: "2,-1", path: "top" },
  { map: "13,8", path: "top" },
  { map: "13,7", path: "top" },
  { map: "13,6", path: "top" },
  { map: "13,5", path: "top" },
  { map: "12,12", path: "top" },
  { map: "12,11", path: "top" },
  { map: "12,10", path: "left" },
  { map: "11,10", path: "top" },
  { map: "11,9", path: "right" },
  { map: "12,9", path: "top" },
  { map: "12,8", path: "right" },
  { map: 88081177, door: 216 }, // Map extérieure de la banque
  { map: 99095051, npcBank: true, path: "410" } // Map intérieure de la banque
]
