const config = {
  MAX_PODS: 90,
  MIN_MONSTERS: 1,
  MAX_MONSTERS: 2,
  ELEMENTS_TO_GATHER: [1, 8]
};

const move = [
  { map: "-2,-19", direction: "bottom", gather: true }, // Incarnam -> Astrub
	{ map: 81267712, direction: "bottom(557)" }, // Incarnam -> Astrub
	{ map: 81267714, direction: "bottom(557)" },
	{ map: 81268739, direction: "right(475)" },
	{ map: 81269763, direction: "right(475)" },
	{ map: 81270787, direction: "bottom(556)" },
	{ map: 80216068, direction: "right(363)" },
	{ map: 80216580, direction: "right(335)" },
	{ map: 80217092, direction: "right" },
	{ map: 80217604, direction: "right" },
	{ map: 80218628, direction: "right" },
  { map: 80219140, direction: "right(139)" },
	{ map: 80219652, direction: "right(251)" },
	{ map: 80220164, direction: "right" },
	{ map: 80220676, custom: talktonpc },
	{ map: 84674566, direction: "top" },
	{ map: "2,-12", direction: "right" },
	{ map: "3,-12", direction: "right" },
	{ map: "4,-12", direction: "top" },
	{ map: "4,-13", direction: "top" },
	{ map: "4,-14", direction: "top(9)" },
	{ map: "7,-19", direction: "left" },
	{ map: "0,-22", gather: true, direction: "right|bottom" },
	{ map: "1,-22", gather: true, direction: "left|right|bottom" },
	{ map: "2,-22", gather: true, direction: "left|right|bottom" },
	{ map: "3,-22", gather: true, direction: "left(336)|right(251)|bottom(557)" },
	{ map: "4,-22", gather: true, direction: "left|right|bottom" },
	{ map: "5,-22", gather: true, direction: "left|bottom" },
	{ map: "-1,-21", gather: true, direction: "right|bottom" },
	{ map: "0,-21", gather: true, direction: "top|left|right|bottom" },
	{ map: "1,-21", gather: true, direction: "top|left|right|bottom" },
	{ map: "3,-20", gather: true, direction: "top|left|right|bottom" },
	{ map: "2,-21", gather: true, direction: "top|left|right|bottom" },
	{ map: "3,-21", gather: true, direction: "top|left|right|bottom" },
	{ map: "4,-21", gather: true, direction: "top|left|right|bottom" },
	{ map: "5,-21", gather: true, direction: "top|left|right|bottom" },
	{ map: "6,-21", gather: true, direction: "left|bottom" },
	{ map: "7,-21", gather: true, direction: "left(448)|bottom(549)" },
	{ map: "-1,-20", gather: true, direction: "top|right|bottom" },
	{ map: "0,-20", gather: true, direction: "top|left|right|bottom" },
	{ map: "1,-20", gather: true, direction: "top|left|right|bottom" },
	{ map: "2,-20", gather: true, direction: "top|left|right|bottom" },
	{ map: "4,-20", gather: true, direction: "top|left|right|bottom" },
	{ map: "5,-20", gather: true, direction: "top|left|right|bottom" },
	{ map: "6,-20", gather: true, direction: "top|left|right|bottom" },
	{ map: "7,-20", gather: true, direction: "top|left|bottom" },
	{ map: "-1,-19", gather: true, direction: "top|right|bottom" },
	{ map: "0,-19", gather: true, direction: "top|left|right|bottom" },
	{ map: "1,-19", gather: true, direction: "top|left|right|bottom" },
	{ map: "2,-19", gather: true, direction: "top|left|right|bottom" },
	{ map: "3,-19", gather: true, direction: "top|left|right|bottom" },
	{ map: "4,-19", direction: "top|left|right|bottom" },
	{ map: "5,-19", gather: true, direction: "top|left|right|bottom" },
	{ map: "6,-19", gather: true, direction: "top|left|right|bottom" },
	{ map: "-1,-18", gather: true, direction: "top|right|bottom" },
	{ map: "0,-18", gather: true, direction: "top|left|right|bottom" },
	{ map: "1,-18", gather: true, direction: "top|left|right" },
	{ map: "2,-18", gather: true, direction: "top|left|right|bottom" },
	{ map: "3,-18", gather: true, direction: "top|left|right|bottom" },
	{ map: "4,-18", gather: true, direction: "top|left|right|bottom" },
	{ map: "5,-18", gather: true, direction: "top|left|right|bottom" },
	{ map: "6,-18", gather: true, direction: "top|left|right|bottom" },
	{ map: "7,-18", gather: true, direction: "top|left|bottom" },
	{ map: "-1,-17", gather: true, direction: "top|right|bottom" },
	{ map: "0,-17", gather: true, direction: "top|left|right|bottom" },
	{ map: "1,-17", gather: true, direction: "left|right|bottom" },
	{ map: "2,-17", gather: true, direction: "top|left|right|bottom" },
	{ map: "3,-17", gather: true, direction: "top|left|right|bottom" },
	{ map: "4,-17", gather: true, direction: "top|left|right|bottom" },
	{ map: "5,-17", gather: true, direction: "top|left|right|bottom" },
	{ map: "6,-17", gather: true, direction: "top|left|right|bottom" },
	{ map: "7,-17", gather: true, direction: "top|left|bottom" },
	{ map: "-1,-16", gather: true, direction: "top|right|bottom" },
	{ map: "0,-16", gather: true, direction: "top|left|right|bottom" },
	{ map: "1,-16", gather: true, direction: "top|left|right|bottom" },
	{ map: "2,-16", gather: true, direction: "top|left|right|bottom" },
	{ map: "3,-16", gather: true, direction: "top|left|right|bottom" },
	{ map: "5,-16", gather: true, direction: "top|left|right|bottom" },
	{ map: "6,-16", gather: true, direction: "top|left|right|bottom" },
	{ map: "7,-16", gather: true, direction: "top(6)|left|bottom(551)" },
	{ map: "-1,-15", gather: true, direction: "top|right|bottom" },
	{ map: "0,-15", gather: true, direction: "top|left|right|bottom" },
	{ map: "1,-15", gather: true, direction: "top|left|right|bottom" },
	{ map: "2,-15", gather: true, direction: "top|left|right|bottom" },
	{ map: "3,-15", gather: true, direction: "top|left|right|bottom" },
	{ map: "4,-15", gather: true, direction: "top|left|right(139)" },
	{ map: "5,-15", gather: true, direction: "top|left(140)|right(111)" },
	{ map: "6,-15", gather: true, direction: "top|left(140)|right" },
	{ map: "7,-15", gather: true, direction: "top|left" },
	{ map: "-1,-14", gather: true, direction: "top" },
	{ map: "0,-14", gather: true, direction: "top|left|right" },
	{ map: "1,-14", gather: true, direction: "top|left|right" },
	{ map: "2,-14", gather: true, direction: "top|left|right" },
	{ map: "3,-14", gather: true, direction: "top|left" }
];

const bank = [
  { map: "3,-16", direction: "right" },
	{ map: "2,-16", direction: "right" },
	{ map: "1,-16", direction: "right" },
	{ map: "0,-16", direction: "right" },
	{ map: "-1,-16", direction: "right" },
	{ map: "-1,-17", direction: "right" },
	{ map: "0,-17", direction: "right" },
	{ map: "1,-17", direction: "right" },
	{ map: "2,-17", direction: "right" },
	{ map: "3,-17", direction: "right" },
	{ map: "3,-18", direction: "right" },
	{ map: "2,-18", direction: "right" },
	{ map: "1,-18", direction: "right" },
	{ map: "0,-18", direction: "right" },
	{ map: "-1,-18", direction: "right" },
	{ map: "-1,-19", direction: "right" },
	{ map: "0,-19", direction: "right" },
	{ map: "1,-19", direction: "right" },
	{ map: "2,-19", direction: "right" },
	{ map: "3,-19", direction: "right" },
	{ map: "3,-20", direction: "right" },
	{ map: "2,-20", direction: "right" },
	{ map: "1,-20", direction: "right" },
	{ map: "0,-20", direction: "right" },
	{ map: "-1,-20", direction: "right" },
	{ map: "-1,-21", direction: "right" },
	{ map: "0,-21", direction: "right" },
	{ map: "1,-21", direction: "right" },
	{ map: "2,-21", direction: "right" },
	{ map: "3,-21", direction: "right" },
	{ map: "3,-22", direction: "right" },
	{ map: "2,-22", direction: "right" },
	{ map: "1,-22", direction: "right" },
	{ map: "0,-22", direction: "right" },
	{ map: "5,-22", direction: "left" },
	{ map: "5,-21", direction: "left" },
	{ map: "5,-19", direction: "left" },
	{ map: "5,-18", direction: "left" },
	{ map: "5,-17", direction: "left" },
	{ map: "5,-16", direction: "left" },
	{ map: "5,-15", direction: "left" },
	{ map: "6,-16", direction: "left" },
	{ map: "6,-17", direction: "left" },
	{ map: "6,-18", direction: "left" },
	{ map: "6,-19", direction: "left" },
	{ map: "6,-21", direction: "left" },
	{ map: "5,-20", direction: "left" },
	{ map: "6,-20", direction: "left" },
	{ map: "7,-20", direction: "left" },
	{ map: "7,-21", direction: "left" },
	{ map: "7,-19", direction: "left" },
	{ map: "7,-18", direction: "left" },
	{ map: "7,-17", direction: "left" },
	{ map: "7,-16", direction: "left" },
	{ map: "7,-15", direction: "left" },
	{ map: "6,-15", direction: "left" },
	{ map: "3,-15", direction: "right" },
	{ map: "2,-15", direction: "right" },
	{ map: "1,-15", direction: "right" },
	{ map: "0,-15", direction: "right" },
	{ map: "-1,-15", direction: "right" },
	{ map: "-1,-14", direction: "top" },
	{ map: "0,-14", direction: "top" },
	{ map: "1,-14", direction: "top" },
	{ map: "2,-14", direction: "top" },
	{ map: "3,-14", direction: "top" },
	{ map: "4,-15", direction: "top" },
	{ map: "4,-17", direction: "bottom" },
	{ map: "4,-18", direction: "bottom" },
	{ map: "4,-19", direction: "bottom" },
	{ map: "4,-20", direction: "bottom" },
	{ map: "4,-21", direction: "bottom" },
	{ map: "4,-22", direction: "bottom" },
	{ map: 84674566, door: 303 },
	{ map: 83887104, npcBank: true, direction: "396" }
];

const phenix = [
  { map: "2,-12", direction: "right", door: 272 }
];

function talktonpc() {
  API.npc.npc(888,3);
  API.npc.reply(-1);
  API.npc.reply(-1);
}
