const config = {
  AUTO_DELETE: [2473,2474,2475,2476,2477,2478,385,310,367,16503,16504,16505],
  MIN_MONSTERS: 2,
  MAX_MONSTERS: 3
};

const move = [
  { map: 153092354, door: 409 },
		{ map: 152043527, direction: "right" },
		{ map: 153092354, door: 409 },
		{ map: 152043527, direction: "right" },
		{ map: "-3,-6", fight: true, direction: "right" },
		{ map: "-2,-6", fight: true, direction: "right" },
		{ map: "-3,-5", fight: true, direction: "top" },
		{ map: "-2,-5", fight: true, direction: "left" },
		{ map: "-1,-6", fight: true, direction: "bottom" },
		{ map: "-1,-5", fight: true, direction: "right" },
		{ map: "0,-5", fight: true, direction: "right" },
		{ map: "-2,-4", fight: true, direction: "top" },
		{ map: "0,-4", fight: true, direction: "left" },
		{ map: "-1,-4", fight: true, direction: "bottom" },
		{ map: "1,-5", fight: true, direction: "right" },
		{ map: "2,-5", fight: true, direction: "right" },
		{ map: "3,-5", fight: true, direction: "bottom" },
		{ map: "1,-4", fight: true, direction: "bottom" },
		{ map: "3,-4", fight: true, direction: "left" },
		{ map: "2,-4", fight: true, direction: "left" },
		{ map: "-2,-3", fight: true, direction: "top" },
		{ map: "-1,-3", fight: true, direction: "left" },
		{ map: "0,-3", fight: true, direction: "top" },
		{ map: "1,-3", fight: true, direction: "right" },
		{ map: "2,-3", fight: true, direction: "right" },
		{ map: "3,-3", fight: true, direction: "bottom" },
		{ map: "3,-2", fight: true, direction: "bottom" },
		{ map: "2,-2", fight: true, direction: "left" },
		{ map: "1,-2", fight: true, direction: "bottom" },
		{ map: "3,-1", fight: true, direction: "left" },
		{ map: "2,-1", fight: true, direction: "top" },
		{ map: "1,-1", fight: true, direction: "bottom" },
		{ map: "1,0", fight: true, direction: "left" },
		{ map: "0,-1", fight: true, direction: "right" },
		{ map: "0,0", fight: true, direction: "left" },
		{ map: "-1,0", fight: true, direction: "left" },
		{ map: "-2,0", fight: true, direction: "top" },
		{ map: "-2,-1", fight: true, direction: "top" },
		{ map: "-2,-2", fight: true, direction: "right" },
		{ map: "-1,-2", fight: true, direction: "right" },
		{ map: "0,-2", fight: true, direction: "top" },
		{ map: 153880835, direction: "left" },
		{ map: 84674566, direction: "left" },
		{ map: 83887104, direction: "396" },
    { map: "3,-16", custom: retourIncarnam }
];

const bank = [
  { map: "-3,-6", direction: "bottom" },
  { map: "-3,-5", direction: "right" },
  { map: "-2,-5", direction: "bottom" },
  { map: "-2,-4", direction: "bottom" },
  { map: "-2,-3", direction: "right" },
  { map: "0,1", direction: "top" },
  { map: "-1,1", direction: "top" },
  { map: "-1,-1", direction: "left" },
  { map: "-1,0", direction: "top" },
  { map: "-2,0", direction: "top" },
  { map: "-1,-1", direction: "top" },
  { map: "0,-3", direction: "right" },
  { map: "-1,-3", direction: "right" },
  { map: "1,-3", direction: "right" },
  { map: "2,-3", direction: "right" },
  { map: "3,-3", direction: "right" },
  { map: "-2,-1", direction: "top" },
  { map: "-2,-2", direction: "top" },
  { map: "-1,-2", direction: "top" },
  { map: "0,-2", direction: "top" },
  { map: "1,-2", direction: "top" },
  { map: "1,-1", direction: "top" },
  { map: "2,-1", direction: "top" },
  { map: "2,-2", direction: "top" },
  { map: "3,-2", direction: "top" },
  { map: "3,-1", direction: "top" },
  { map: "1,0", direction: "top" },
  { map: "2,0", direction: "top" },
  { map: "-1,-4", direction: "bottom" },
  { map: "-1,-5", direction: "bottom" },
  { map: "0,-5", direction: "bottom" },
  { map: "1,-5", direction: "bottom" },
  { map: "2,-5", direction: "bottom" },
  { map: "3,-5", direction: "bottom" },
  { map: "0,-4", direction: "bottom" },
  { map: "1,-4", direction: "bottom" },
  { map: "2,-4", direction: "bottom" },
  { map: "3,-4", direction: "bottom" },
  { map: "4,-4", direction: "left" },
  { map: "-2,-6", direction: "bottom" },
  { map: "-1,-6", direction: "bottom" },
  { map: "0,0", direction: "left" },
  { map: "5,1", direction: "left" },
  { map: "4,1", direction: "top" },
  { map: "3,1", direction: "top" },
  { map: "3,0", direction: "top" },
  { map: "4,-1", direction: "bottom" },
  { map: "5,-1", direction: "bottom" },
  { map: "4,0", direction: "left" },
  { map: "5,0", direction: "left" },
  { map: 153880835, custom: DescendreAstrub },
  { map: "-1,-21", direction: "right" },
  { map: "-1,-20", direction: "right" },
  { map: "-1,-19", direction: "right" },
  { map: "-1,-18", direction: "right" },
  { map: "-1,-17", direction: "right" },
  { map: "-1,-16", direction: "right" },
  { map: "-1,-15", direction: "right" },
  { map: "-1,-14", direction: "right" },
  { map: "0,-14", direction: "right" },
  { map: "0,-15", direction: "right" },
  { map: "0,-16", direction: "right" },
  { map: "0,-17", direction: "right" },
  { map: "0,-18", direction: "right" },
  { map: "0,-19", direction: "right" },
  { map: "0,-20", direction: "right" },
  { map: "0,-21", direction: "right" },
  { map: "0,-22", direction: "right" },
  { map: "1,-22", direction: "right" },
  { map: "1,-21", direction: "right" },
  { map: "1,-20", direction: "right" },
  { map: "1,-19", direction: "right" },
  { map: "1,-18", direction: "right" },
  { map: "1,-17", direction: "right" },
  { map: "1,-16", direction: "right" },
  { map: "1,-15", direction: "right" },
  { map: "1,-14", direction: "right" },
  { map: "2,-14", direction: "right" },
  { map: "2,-15", direction: "right" },
  { map: "2,-16", direction: "right" },
  { map: "2,-17", direction: "right" },
  { map: "2,-18", direction: "right" },
  { map: "2,-19", direction: "right" },
  { map: "2,-20", direction: "right" },
  { map: "2,-21", direction: "right" },
  { map: "2,-22", direction: "right" },
  { map: "3,-22", direction: "right" },
  { map: "3,-21", direction: "right" },
  { map: "3,-20", direction: "right" },
  { map: "3,-19", direction: "right" },
  { map: "3,-18", direction: "right" },
  { map: "3,-17", direction: "right" },
  { map: "3,-16", direction: "right" },
  { map: "3,-15", direction: "right" },
  { map: "3,-14", direction: "top" },
  { map: "5,-22", direction: "left" },
  { map: "5,-21", direction: "left" },
  { map: "5,-20", direction: "left" },
  { map: "5,-19", direction: "left" },
  { map: "5,-18", direction: "left" },
  { map: "5,-17", direction: "left" },
  { map: "5,-16", direction: "left" },
  { map: "5,-15", direction: "left" },
  { map: "6,-15", direction: "left" },
  { map: "7,-15", direction: "left" },
  { map: "7,-16", direction: "left" },
  { map: "6,-16", direction: "left" },
  { map: "6,-17", direction: "left" },
  { map: "7,-17", direction: "left" },
  { map: "7,-18", direction: "left" },
  { map: "6,-18", direction: "left" },
  { map: "6,-19", direction: "left" },
  { map: "7,-19", direction: "left" },
  { map: "7,-20", direction: "left" },
  { map: "6,-20", direction: "left" },
  { map: "7,-21", direction: "left" },
  { map: "6,-21", direction: "left" },
  { map: "4,-22", direction: "bottom" },
  { map: "4,-21", direction: "bottom" },
  { map: "4,-20", direction: "bottom" },
  { map: "4,-19", direction: "bottom" },
  { map: "4,-18", direction: "bottom" },
  { map: "4,-17", direction: "bottom" },
  { map: "4,-15", direction: "top" },
  { map: 84674566, door: 303 },
  { map: 83887104, npcBank: true, direction: "396" },
];

const phenix = [
  { map: "5,0", direction: "left" },
  { map: "4,0", direction: "left" },
  { map: "5,-1", direction: "bottom" },
  { map: "4,-1", direction: "bottom" },
  { map: "4,1", direction: "top" },
  { map: "3,1", direction: "top" },
  { map: "3,0", direction: "top" },
  { map: "3,-1", direction: "left" },
  { map: "2,-1", phenix: 232 },
];

function DescendreAstrub() {
  API.npc.npc(2889, 3);
  API.npc.reply(-1);
  API.npc.reply(-1);
}

function retourIncarnam() {
  API.map.useById(489378, -1);
}
